fix: accounts.models.User: adjust patching of help_text
The custom accounts.models.User model patches Django AbstractUser
with increased maximum username length.

This patching also aimed to update help_text

However, the internal structure changed and the code (in a try block)
was (silently) failing with:

  AttributeError: '__proxy__' object has no attribute '_proxy____args'

One impact of this failed update was that Django was trying to create
spurious migrations (that would just update help_text)

Fix this by avoiding the Django model field internals and use field.help_text
directly (converted to a string).

It gets replaced with a string anyway in the subsequent step.