Django 1.8: locales in management commands
The contacts.py command was printing unicode, and after Django 1.8 upgrade, started failing with:

    UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 1: ordinal not in range(128)

Django versions prior to 1.8 were enforcing the "en-us" locale which was creating the need to wrap stdout with another layer of unicode encoding.

Django 1.8 now just switches off translations - but honours the leave_locale_alone option.

* Set this option and rely on Django default handling of unicode.
* Also remove the no longer needed wrapped sys.stdout
* Add encoding header to indicate the source code is in utf-8
* Normalize encoding name from UTF8 to UTF-8

More information at

https://docs.djangoproject.com/en/1.8/howto/custom-management-commands/#management-commands-and-locales